name: Docker Image CI/CD for IDG2671

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 23.x
          cache: npm
      - run: npm ci
      - name: some type of testing that we've doing
        run: npm run test

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
        - uses: actions/checkout@v3
        - uses: docker/login-action@v3
          with:
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_TOKEN }}
        - name: build and push our image to dockerhub
          uses: docker/build-push-action@v5
          with:
            context: .
            file: Dockerfile
            push: true
            tags: ${{ secrets.DOCKERHUB_USERNAME }}/idg2671_25:latest
